#!/usr/bin/env bash
# Seed wiki pages from raw/ source tree.
#
# Scans RAW_DIR for .c/.h files and creates one seed page per translation
# unit (a .c and its same-name .h merged) under WIKI_DIR, mirroring the
# raw/ directory layout. Also updates wiki/_meta/coverage.json (preserving
# existing entries) and writes wiki/<raw-top>/_index.md.
#
# Pages contain front-matter only and a stub body — the LLM updater fills
# them in later via scripts/update_wiki.py.

set -euo pipefail

RAW_DIR="raw"
WIKI_DIR="wiki"
FORCE=0
DRY_RUN=0
PER_FILE=0

usage() {
  cat <<EOF
Usage: $0 [options]

Options:
  --raw <path>     raw root (default: raw)
  --wiki <path>    wiki root (default: wiki)
  --per-file       one page per file (default: merge .c+.h into one page)
  --force          overwrite existing seed pages
  -n, --dry-run    print plan, do not write
  -h, --help       show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --raw) RAW_DIR="$2"; shift 2 ;;
    --wiki) WIKI_DIR="$2"; shift 2 ;;
    --per-file) PER_FILE=1; shift ;;
    --force) FORCE=1; shift ;;
    -n|--dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown arg: $1" >&2; usage; exit 2 ;;
  esac
done

[[ -d "$RAW_DIR" ]] || { echo "raw dir not found: $RAW_DIR" >&2; exit 1; }

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

RAW_TOP="$(basename "$RAW_DIR")"

# 1. enumerate .c/.h
find "$RAW_DIR" -type f \( -name '*.c' -o -name '*.h' \) | LC_ALL=C sort > "$TMP/all.txt"

# 2. group → tsv: <wiki-rel-dir>\t<base>\t<file1,file2,...>
#    Covers are written relative to RAW_DIR (so raw/<rest> → <rest>),
#    matching KERNEL_ROOT = raw/ in scripts/_meta_io.py.
python3 - "$TMP/all.txt" "$TMP/map.tsv" "$RAW_DIR" "$PER_FILE" <<'PY'
import collections, os, sys

src, out, raw_dir, per_file = sys.argv[1:]
per_file = per_file == "1"
raw_dir = raw_dir.rstrip("/")
raw_top = os.path.basename(raw_dir)

groups = collections.defaultdict(list)
with open(src) as f:
    for line in f:
        p = line.strip()
        if not p:
            continue
        under = p[len(raw_dir) + 1:]
        d_under, fname = os.path.split(under)
        base, ext = os.path.splitext(fname)
        wiki_dir_rel = raw_top + (("/" + d_under) if d_under else "")
        # cover paths are relative to KERNEL_ROOT (raw/), so strip raw_top.
        cover_rel = under
        page_base = fname if per_file else base
        groups[(wiki_dir_rel, page_base)].append(cover_rel)

with open(out, "w") as fh:
    for (d, b), files in sorted(groups.items()):
        files.sort()
        fh.write(f"{d}\t{b}\t{','.join(files)}\n")
PY

SECTIONS_DIR="$TMP/sections"
mkdir -p "$SECTIONS_DIR"
: > "$TMP/dirs.txt"

CREATED=0; SKIPPED=0; WOULD=0

while IFS=$'\t' read -r d b files; do
  page_rel="$d/$b.md"
  page_path="$WIKI_DIR/$page_rel"

  sect_id="$(printf '%s' "$d" | tr '/ ' '__')"
  printf '%s\n' "$b" >> "$SECTIONS_DIR/$sect_id"
  printf '%s\n' "$d" >> "$TMP/dirs.txt"

  if [[ -f "$page_path" && $FORCE -eq 0 ]]; then
    SKIPPED=$((SKIPPED + 1))
    echo "skip   $page_rel"
    continue
  fi

  if [[ $DRY_RUN -eq 1 ]]; then
    WOULD=$((WOULD + 1))
    echo "would  $page_rel    [covers: $files]"
    continue
  fi

  mkdir -p "$(dirname "$page_path")"
  {
    echo '---'
    echo "title: $b"
    echo 'kind: entity'
    echo 'covers:'
    IFS=',' read -ra files_arr <<< "$files"
    for f in "${files_arr[@]}"; do echo "  - $f"; done
    echo 'last_synced_sha: null'
    echo 'last_synced: null'
    echo 'sources: []'
    echo '---'
    echo
    echo "# $b"
    echo
    echo "> Seed page — \`scripts/seed_pages.sh\`가 생성. LLM이 채울 자리."
    echo
    echo '## Purpose'
    echo 'TODO'
    echo
    echo '## Public API'
    echo 'TODO'
    echo
    echo '## Internal flow'
    echo 'TODO'
    echo
    echo '## Source files'
    for f in "${files_arr[@]}"; do echo "- \`$f\`"; done
  } > "$page_path"
  CREATED=$((CREATED + 1))
  echo "create $page_rel"
done < "$TMP/map.tsv"

if [[ $DRY_RUN -eq 1 ]]; then
  echo
  echo "dry-run: would create $WOULD pages (skipped $SKIPPED existing)"
  exit 0
fi

# 3. write seed index
INDEX_PATH="$WIKI_DIR/$RAW_TOP/_index.md"
mkdir -p "$(dirname "$INDEX_PATH")"
NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
{
  echo "# $RAW_TOP — seeded pages"
  echo
  echo "> Auto-generated by \`scripts/seed_pages.sh\` at $NOW."
  echo
  LC_ALL=C sort -u "$TMP/dirs.txt" | while read -r d; do
    [[ -n "$d" ]] || continue
    echo "## $d"
    sect_id="$(printf '%s' "$d" | tr '/ ' '__')"
    [[ -f "$SECTIONS_DIR/$sect_id" ]] || { echo; continue; }
    sub="${d#$RAW_TOP}"; sub="${sub#/}"
    LC_ALL=C sort -u "$SECTIONS_DIR/$sect_id" | while read -r b; do
      if [[ -z "$sub" ]]; then
        echo "- [$b](./$b.md)"
      else
        echo "- [$b](./$sub/$b.md)"
      fi
    done
    echo
  done
} > "$INDEX_PATH"
echo "index  $RAW_TOP/_index.md"

# 4. merge coverage.json
COVERAGE="$WIKI_DIR/_meta/coverage.json"
python3 - "$COVERAGE" "$TMP/map.tsv" <<'PY'
import json, pathlib, sys

cov_path, map_path = sys.argv[1:]
p = pathlib.Path(cov_path)
if p.exists():
    cov = json.loads(p.read_text())
else:
    cov = {"schema_version": 2, "subtree_shas": {}, "pages": {}}
cov.setdefault("schema_version", 2)
cov.setdefault("subtree_shas", {})
cov.setdefault("pages", {})

added = merged = 0
with open(map_path) as f:
    for line in f:
        line = line.rstrip("\n")
        if not line:
            continue
        d, b, files = line.split("\t", 2)
        files = files.split(",")
        key = f"{d}/{b}.md"
        entry = cov["pages"].get(key)
        if entry is None:
            cov["pages"][key] = {
                "kind": "entity",
                "covers": files,
                "last_synced_sha": None,
                "last_synced": None,
            }
            added += 1
        else:
            old = entry.get("covers") or []
            new = sorted(set(old) | set(files))
            if list(new) != list(old):
                entry["covers"] = new
                merged += 1

p.parent.mkdir(parents=True, exist_ok=True)
p.write_text(json.dumps(cov, indent=2, sort_keys=True) + "\n")
print(f"coverage.json: +{added} added, ~{merged} merged")
PY

echo
echo "done. created=$CREATED skipped=$SKIPPED"
